from os import PathLike
from typing import Any, Callable, Generic, Literal, Mapping, Sequence, TypeVar

INTEROP_SCHEMA_VERSION: int
ProviderKind = Literal["open_ai", "anthropic", "gemini", "ollama", "open_ai_compatible"]
JobState = Literal["queued", "running", "cancelling", "publishing", "completed", "failed", "cancelled"]
CancelOutcome = Literal["requested", "too_late", "already_finished"]
AiRole = Literal["embedding", "organizer", "synthesis", "critic"]
_T = TypeVar("_T")

class OkcError(RuntimeError):
    code: str
    category: str
    message: str
    retryable: bool
    details: Mapping[str, Any]

class ProviderProfile:
    name: str
    kind: ProviderKind
    endpoint: str
    model: str
    api_key_env: str | None
    timeout_ms: int
    max_response_bytes: int
    max_input_bytes: int
    max_batch_items: int
    options: Mapping[str, Any]
    def __init__(self, name: str, kind: ProviderKind, endpoint: str, model: str, api_key_env: str | None = None, timeout_ms: int = 120_000, max_response_bytes: int = 16 * 1024 * 1024, max_input_bytes: int = 64 * 1024 * 1024, max_batch_items: int = 2_048, options: Mapping[str, Any] = ...) -> None: ...

class SourceInput:
    source_id: str
    path: PathLike[str] | str
    owner_display_name: str | None
    snapshot_id: str | None
    def __init__(self, source_id: str, path: PathLike[str] | str, owner_display_name: str | None = None, snapshot_id: str | None = None) -> None: ...

class Job(Generic[_T]):
    @property
    def state(self) -> JobState: ...
    def events(self) -> list[dict[str, Any]]: ...
    def result(self) -> _T: ...
    def cancel(self) -> CancelOutcome: ...

class OkcClient:
    provider_profiles: tuple[ProviderProfile, ...]
    def __init__(self, provider_profiles: Sequence[ProviderProfile] = (), *, max_concurrent_jobs: int = 4) -> None: ...
    def api_info(self) -> dict[str, Any]: ...
    def create_project(self, path: PathLike[str] | str, *, name: str, curator_id: str, policy_version: str = "policy-v3", language: str | None = None) -> Job[Project]: ...
    def open_project(self, path: PathLike[str] | str) -> Job[Project]: ...
    def test_provider(self, name: str) -> Job[dict[str, Any]]: ...
    def verify_artifact(self, path: PathLike[str] | str) -> Job[dict[str, Any]]: ...
    def explain_artifact(self, path: PathLike[str] | str, *, output_path: str | None = None, package: bool = False, limit: int | None = None, cursor: str | None = None) -> Job[dict[str, Any]]: ...

class Project:
    @property
    def path(self) -> str: ...
    def manifest(self) -> Job[dict[str, Any]]: ...
    def status(self) -> Job[dict[str, Any]]: ...
    def add_source(self, source: SourceInput) -> Job[dict[str, Any]]: ...
    def rebind_source(self, source_id: str, path: PathLike[str] | str, *, snapshot_id: str | None = None) -> Job[dict[str, Any]]: ...
    def replace_sources(self, sources: Sequence[SourceInput]) -> Job[dict[str, Any]]: ...
    def set_language(self, language: str | None) -> Job[dict[str, Any]]: ...
    def set_ai_route(self, profile_name: str, *, role: AiRole | None = None) -> Job[dict[str, Any]]: ...
    def preflight(self) -> Job[dict[str, Any]]: ...
    def integrate(self, *, allow_remote_provider: bool, remote_disclosure_confirmed: bool) -> Job[dict[str, Any]]: ...
    def taxonomy(self) -> Job[dict[str, Any]]: ...
    def approve_taxonomy(self, *, edited_clusters: Sequence[Mapping[str, Any]] | None = None, rationale: str | None = None) -> Job[dict[str, Any]]: ...
    def clusters(self) -> Job[dict[str, Any]]: ...
    def approve_cluster(self, cluster_id: str, *, omission_rationales: Mapping[str, str] | None = None, minor_waivers: Mapping[str, str] | None = None) -> Job[dict[str, Any]]: ...
    def regenerate_cluster(self, cluster_id: str, feedback: str, *, allow_remote_provider: bool, remote_disclosure_confirmed: bool) -> Job[dict[str, Any]]: ...
    def compile(self, output: PathLike[str] | str) -> Job[dict[str, Any]]: ...
