class NativeJob:
    def state(self) -> str: ...
    def events_json(self) -> str: ...
    def result_json(self) -> str: ...
    def cancel(self) -> str: ...

class NativeClient:
    def __init__(self, profiles_json: str = "[]", max_concurrent_jobs: int | None = None) -> None: ...
    def api_info_json(self) -> str: ...
    def create_project(self, path: str, name: str, curator_id: str, policy_version: str, language: str | None = None) -> NativeJob: ...
    def open_project(self, path: str) -> NativeJob: ...
    def project_handle(self, path: str) -> NativeProject: ...
    def test_provider(self, name: str) -> NativeJob: ...
    def verify_artifact(self, path: str) -> NativeJob: ...
    def explain_artifact(self, path: str, output_path: str) -> NativeJob: ...

class NativeProject:
    def path(self) -> str: ...
    def manifest(self) -> NativeJob: ...
    def status(self) -> NativeJob: ...
    def add_source(self, source_json: str) -> NativeJob: ...
    def rebind_source(self, source_id: str, path: str, snapshot_id: str | None = None) -> NativeJob: ...
    def replace_sources(self, sources_json: str) -> NativeJob: ...
    def set_language(self, language: str | None) -> NativeJob: ...
    def set_ai_route(self, role: str | None, profile_name: str) -> NativeJob: ...
    def preflight(self) -> NativeJob: ...
    def integrate(self, allow_remote_provider: bool, remote_disclosure_confirmed: bool) -> NativeJob: ...
    def taxonomy(self) -> NativeJob: ...
    def approve_taxonomy(self, edited_clusters_json: str | None = None, rationale: str | None = None) -> NativeJob: ...
    def clusters(self) -> NativeJob: ...
    def approve_cluster(self, cluster_id: str, omission_rationales_json: str = "{}", minor_waivers_json: str = "{}") -> NativeJob: ...
    def regenerate_cluster(self, cluster_id: str, feedback: str, allow_remote_provider: bool, remote_disclosure_confirmed: bool) -> NativeJob: ...
    def compile(self, output: str) -> NativeJob: ...

def interop_schema_version() -> int: ...
